/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://biz6qtmcsjdqvbz7qtg4momynq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5jtaf7nesveh5frxrr4cohknhq",
    "aws_cognito_identity_pool_id": "us-east-1:7ca98193-7fd7-40d1-ba32-a61c35ce4976",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_e9DueqsLg",
    "aws_user_pools_web_client_id": "1t0umk3jk7peibf484cd1ppgjm",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplifyapp-storage-46576f43f537a-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
